packages:
  - "packages/*"
  # - "packages/api"
  # - "packages/shared"
  # - "packages/vue-vendor"
  # - "projects/*"
  - "projects/desktop"
  - "projects/web"
  # - "projects/h5"
  # - "projects/applet"
