// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BgMask: typeof import('./src/components/bg-mask/index.vue')['default']
    CardMask: typeof import('./src/components/card-mask/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InverseIcon: typeof import('./src/components/inverse-icon/index.vue')['default']
    LineItem: typeof import('./src/components/multiline-swiper/components/LineItem.vue')['default']
    ListTitle: typeof import('./src/components/song-list-content/components/ListTitle.vue')['default']
    LoadingSpinner: typeof import('./src/components/loading-spinner/index.vue')['default']
    MiniPlayer: typeof import('./src/components/layout/MiniPlayer.vue')['default']
    MultilineSwiper: typeof import('./src/components/multiline-swiper/index.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    PlaylistItem: typeof import('./src/components/playlist-item/index.vue')['default']
    RankListCard: typeof import('./src/components/rank-list-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongItem: typeof import('./src/components/song-item/index.vue')['default']
    SongListContent: typeof import('./src/components/song-list-content/index.vue')['default']
    SongListPoster: typeof import('./src/components/song-list-poster/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    SvgIconInverse: typeof import('./src/components/SvgIconInverse/index.vue')['default']
    SvgProgress: typeof import('./src/components/svg-progress/index.vue')['default']
    Tabbar: typeof import('./src/components/layout/Tabbar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwiper: typeof import('vant/es')['Swiper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
